"""Generated index.md: every wiki page, grouped by type, with its summary."""

from __future__ import annotations

from .naming import key
from .pages import Page, iter_pages
from .vault import TYPE_DIRS, Vault

NOTICE = "<!-- Generated by `wiki index`. Do not edit by hand: changes will be overwritten. -->"
HEADINGS = {"source": "Sources", "entity": "Entities", "concept": "Concepts", "analysis": "Analyses"}


def entry(page: Page) -> str:
    return f"- {page.link} — {page.summary}" if page.summary else f"- {page.link}"


def render(pages: list[Page]) -> str:
    groups: dict[str | None, list[Page]] = {t: [] for t in TYPE_DIRS}
    for p in pages:
        groups.setdefault(p.folder_type, []).append(p)
    lines = [NOTICE, "", "# Index", ""]
    sections = [(t, HEADINGS[t]) for t in TYPE_DIRS]
    if groups.get(None):
        sections.append((None, "Other"))
    for t, heading in sections:
        items = sorted(groups[t], key=lambda p: (key(p.stem), p.stem))
        lines.append(f"## {heading}")
        lines.append("")
        if items:
            lines.extend(entry(p) for p in items)
        else:
            lines.append("_None yet._")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def expected(vault: Vault) -> str:
    return render(iter_pages(vault))


def is_stale(vault: Vault) -> bool:
    try:
        current = vault.index_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return True
    return current != expected(vault)


def write(vault: Vault) -> dict:
    pages = iter_pages(vault)
    text = render(pages)
    try:
        changed = vault.index_path.read_text(encoding="utf-8") != text
    except FileNotFoundError:
        changed = True
    if changed:
        vault.index_path.write_text(text, encoding="utf-8")
    counts = {t: sum(1 for p in pages if p.folder_type == t) for t in TYPE_DIRS}
    return {"path": vault.rel(vault.index_path), "changed": changed, "pages": len(pages), "counts": counts}
